In [1]:
import numpy as np
import pandas as pd

In [2]:
data_dic = {'A': [1, 2, None, 4, np.nan],
           'B': [np.nan, np.nan, np.nan, np.nan, np.nan],
           'C': [11, 12, 13, 14, 15],
           'D': [16, np.nan, 18, 19, 20]}

df = pd.DataFrame(data_dic)
df

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [3]:
# pip install scikit-learn
import sklearn
sklearn.__version__

'1.5.2'

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
df2 = df.copy()

In [6]:
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [7]:
imputer = SimpleImputer(strategy='constant', fill_value=-1)
df2['A'] = imputer.fit_transform(df2[['A']])
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2 -1.0 NaN  13  18.0
3  4.0 NaN  14  19.0
4 -1.0 NaN  15  20.0

In [8]:
df2 = df.copy()

In [9]:
imputer = SimpleImputer(strategy='mean')
df2['A'] = imputer.fit_transform(df2[['A']])
df2

A   B   C     D
0  1.000000 NaN  11  16.0
1  2.000000 NaN  12   NaN
2  2.333333 NaN  13  18.0
3  4.000000 NaN  14  19.0
4  2.333333 NaN  15  20.0

In [10]:
imputer = SimpleImputer(strategy='mean')
df2 = imputer.fit_transform(df2) # column B will be deleted for null values
df2

/home/user/data-science-notes/.venv/lib/python3.11/site-packages/sklearn/impute/_base.py:598: UserWarning: Skipping features without any observed values: ['B']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(


array([[ 1.        , 11.        , 16.        ],
       [ 2.        , 12.        , 18.25      ],
       [ 2.33333333, 13.        , 18.        ],
       [ 4.        , 14.        , 19.        ],
       [ 2.33333333, 15.        , 20.        ]])

In [11]:
df

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [12]:
df2

array([[ 1.        , 11.        , 16.        ],
       [ 2.        , 12.        , 18.25      ],
       [ 2.33333333, 13.        , 18.        ],
       [ 4.        , 14.        , 19.        ],
       [ 2.33333333, 15.        , 20.        ]])

In [13]:
df2 = df.copy()

In [14]:
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [15]:
imputer = SimpleImputer(strategy='median')
df2['A'] = imputer.fit_transform(df2[['A']])
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  2.0 NaN  13  18.0
3  4.0 NaN  14  19.0
4  2.0 NaN  15  20.0

In [16]:
df2 = df.copy()

In [17]:
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [18]:
imputer = SimpleImputer(strategy='median')
df2['D'] = imputer.fit_transform(df2[['D']])
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12  18.5
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [19]:
df2 = df.copy()

In [20]:
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [21]:
imputer = SimpleImputer(strategy='median')
df2['A'] = imputer.fit_transform(df2[['A']])
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  2.0 NaN  13  18.0
3  4.0 NaN  14  19.0
4  2.0 NaN  15  20.0

In [22]:
# creating a new DataFrame
data_dic = {'A':[1,2,np.nan,4,np.nan],
            'B':[np.nan,np.nan,np.nan,np.nan,np.nan],
            'C':[11,12,13,14,15],
            'D':[16,18,np.nan,19,18]}

df2 = pd.DataFrame(data_dic)
df2


A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12  18.0
2  NaN NaN  13   NaN
3  4.0 NaN  14  19.0
4  NaN NaN  15  18.0

In [23]:
imputer = SimpleImputer(strategy='most_frequent')
df2['D'] = imputer.fit_transform(df2[['D']])
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12  18.0
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  18.0

In [24]:
df

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [25]:
from sklearn.impute import KNNImputer

In [26]:
df2 = df.copy()
df2

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [27]:
knn_imputer = KNNImputer(n_neighbors=2, weights='uniform')
A1 = knn_imputer.fit_transform(df2)
A1

array([[ 1., 11., 16.],
       [ 2., 12., 17.],
       [ 3., 13., 18.],
       [ 4., 14., 19.],
       [ 3., 15., 20.]])

In [28]:
df2 = pd.DataFrame(data=A1, columns=['A', 'C', 'D'])
df2

A     C     D
0  1.0  11.0  16.0
1  2.0  12.0  17.0
2  3.0  13.0  18.0
3  4.0  14.0  19.0
4  3.0  15.0  20.0

In [29]:
df

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [30]:
df.fillna(value=0)

A    B   C     D
0  1.0  0.0  11  16.0
1  2.0  0.0  12   0.0
2  0.0  0.0  13  18.0
3  4.0  0.0  14  19.0
4  0.0  0.0  15  20.0

In [31]:
df

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [32]:
df.fillna(value=0, inplace=True)

In [33]:
df

A    B   C     D
0  1.0  0.0  11  16.0
1  2.0  0.0  12   0.0
2  0.0  0.0  13  18.0
3  4.0  0.0  14  19.0
4  0.0  0.0  15  20.0