In [1]:
%%html
<h3>indexing & slicing 2-d arrays</h3>

In [2]:
import numpy as np
np.__version__

'2.1.3'

In [5]:
array = np.arange(24)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
array_2d = array.reshape(6, 4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
array.shape = (6, 4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
type(array)

numpy.ndarray

In [10]:
type(array_2d)

numpy.ndarray

In [11]:
array_2d[2]

array([ 8,  9, 10, 11])

In [12]:
array_2d[3]

array([12, 13, 14, 15])

In [16]:
array_2d[-3]

array([12, 13, 14, 15])

In [17]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
row = 5
column = 2
array_2d[row, column]

np.int64(22)

In [19]:
array_2d[5, 2]

np.int64(22)

In [20]:
array_2d[5][2]

np.int64(22)

In [22]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
array_2d[:5, :3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [24]:
array_2d[:2, :2]

array([[0, 1],
       [4, 5]])

In [27]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
array_2d[[2, 3, 4]]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
array_2d[[5, 2]]

array([[20, 21, 22, 23],
       [ 8,  9, 10, 11]])

In [32]:
array_2d[5, 2]

np.int64(22)

In [33]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
array_2d[:, [2]]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [36]:
array_2d[[3, 0, 1]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])