In [1]:
%%html
<h3>Broadcasting Array:</h3>

In [2]:
import numpy as np
np.__version__

'2.1.3'

In [3]:
array_1d = np.arange(0,10)

In [4]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
array_1d.ndim

1

In [15]:
type(array_1d)

numpy.ndarray

In [16]:
array_1d.dtype

dtype('int64')

In [17]:
array_1d.size

10

In [18]:
array_1d.itemsize

8

In [19]:
array_1d.shape

(10,)

In [20]:
array_1d.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
array_1d.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
type(array_1d.reshape(5,2))

numpy.ndarray

In [23]:
array_1d.reshape(5,2).ndim

2

In [25]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array_1d[0:5]

array([0, 1, 2, 3, 4])

In [28]:
array_1d 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array_1d[0:5]=500

In [30]:
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [32]:
array_2d = np.zeros((4,4))
array_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
array_2d = np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
array_2d[0]

array([1., 1., 1., 1.])

In [41]:
array_2d[0] = 300

In [42]:
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [44]:
array_2d > 400

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [43]:
array_2d + 300

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [45]:
array_2d + 300 > 400

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [46]:
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [51]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print("First array: ")
print(a)
print("\n")

print("Second array: ")
print(b)
print("\n")

print("First array + Second array: ")
print(a+b)
print("\n")

First array: 
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array: 
[1. 2. 3.]


First array + Second array: 
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


