In [4]:
# Numpy arrays = numerical python
# numpy developed by Travis Oliphant

In [5]:
import numpy as np

In [6]:
np.__version__

'2.1.3'

In [7]:
list = [0, 1, 2]

In [8]:
list

[0, 1, 2]

In [9]:
type(list)

list

In [11]:
list * 2

[0, 1, 2, 0, 1, 2]

In [12]:
arr = np.array(list)

In [13]:
arr

array([0, 1, 2])

In [19]:
arr * 2

array([0, 2, 4])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr = np.array([0, 1, 2])

In [22]:
arr

array([0, 1, 2])

In [23]:
type(arr)

numpy.ndarray

In [25]:
arr * 2

array([0, 2, 4])

In [27]:
my_list = [-1, 0, 1]
my_list

[-1, 0, 1]

In [28]:
print(my_list)

[-1, 0, 1]


In [29]:
type(my_list)

list

In [30]:
my_array = np.array([my_list])
my_array

array([[-1,  0,  1]])

In [31]:
type(my_array)

numpy.ndarray

In [32]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [33]:
type(my_matrix)

list

In [34]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [35]:
type(matrix_one)

numpy.ndarray

In [36]:
my_tuple = (-1, 0, 1)
my_array = np.array(my_tuple)
my_array

array([-1,  0,  1])

In [37]:
type(my_array)

numpy.ndarray

In [38]:
my_array = np.array([3, 5, 6])
my_array

array([3, 5, 6])

In [39]:
type(my_array)

numpy.ndarray

In [40]:
my_array = np.array([3, 5, 'a'])
my_array

array(['3', '5', 'a'], dtype='<U21')

In [41]:
type(my_array)

numpy.ndarray

In [42]:
my_list = [3, 4, 'a']
my_list

[3, 4, 'a']