In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
arr = np.array([2, 4, 5])
arr

array([2, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(1)

array([1.])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((3, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones(10, dtype='int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [20]:
np.ones((3, 2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [22]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.full((5, 6), 99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [25]:
np.random.rand(4, 2)

array([[0.37645231, 0.80174226],
       [0.51249597, 0.56295401],
       [0.07126574, 0.82309733],
       [0.22309112, 0.19629924]])

In [26]:
np.random.rand(3, 3)

array([[0.33634872, 0.65519655, 0.87133823],
       [0.01719144, 0.34182536, 0.77132481],
       [0.94208572, 0.26173392, 0.06858998]])

In [28]:
np.random.randint(1, 100, 10)

array([61, 68, 18,  9, 88, 97,  4,  1, 84, 33], dtype=int32)

In [29]:
np.random.randint(1, 100, 10)

array([91, 88, 81, 30, 14, 98, 93, 85, 80, 18], dtype=int32)

In [30]:
np.random.randint(1, 100, 10)

array([28,  1, 80, 62, 69, 42,  6, 62, 71, 58], dtype=int32)

In [32]:
np.random.randint(-4, 8, size=(3, 3))

array([[ 3,  6,  2],
       [-3,  7, -4],
       [ 1,  6,  0]], dtype=int32)

In [33]:
np.random.randint(-4, 8, size=(3, 3))

array([[-2, -3,  0],
       [-3, -4, -1],
       [ 2, -1,  7]], dtype=int32)

In [34]:
np.random.randint(-4, 8, size=(3, 3))

array([[ 2,  5,  5],
       [-2,  4, -4],
       [-3,  7, -1]], dtype=int32)

In [35]:
np.random.randn(20)

array([-0.27096253,  1.60786925,  0.67270457,  1.16417365,  1.05096313,
        0.76162638,  0.2134566 , -0.74285948, -1.32530856,  0.04267617,
       -0.37261613,  0.19570686,  0.23299392,  1.79334225,  1.15478454,
        0.67500276, -0.95939125,  0.17486272,  0.38857129,  1.06466732])

In [37]:
np.random.randn(20)

array([ 0.80856574, -0.33607287, -0.16461568,  3.07728481,  0.41955128,
       -1.57085209, -0.83126243, -0.21245435,  1.72593715, -1.58866677,
       -1.39527378, -0.09301178, -1.41721833, -0.35912108, -0.99802133,
       -0.58806744,  0.66616467,  1.60796238, -0.85199668,  0.88276027])

In [38]:
np.random.randn(5)

array([-2.13218654, -1.32164367, -0.82338637,  1.98284434, -1.22404642])

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(5, dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)