In [24]:
%%html
<h2>arange</h2>

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [17]:
np.arange(3, 10, 2, dtype='float')

array([3., 5., 7., 9.])

In [20]:
np.arange(0, 10, 2, dtype='float')

array([0., 2., 4., 6., 8.])

In [21]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.arange(0, 10, 2, dtype='float')

array([0., 2., 4., 6., 8.])

In [23]:
%%html
<h2>linspace</h2>

In [26]:
np.linspace(1, 2, 10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [27]:
np.linspace(1, 2, 10, retstep=True)

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 np.float64(0.1111111111111111))

In [28]:
np.linspace(1, 2, 10, retstep=False)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [29]:
np.linspace(9, 15, 20, retstep=True)

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 np.float64(0.3157894736842105))

In [30]:
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 np.float64(0.3157894736842105))

In [32]:
np.linspace(0, 15, 30)

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

In [33]:
np.linspace(0, 15, 30, retstep=True)

(array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
         2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
         5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
         7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
        10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
        12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ]),
 np.float64(0.5172413793103449))