In [1]:
%%html
<h3>indexing & slicing 1-d arrays</h3>

In [3]:
import numpy as np
np.__version__

'2.1.3'

In [4]:
array_1d = np.array([-10, -2, 0, 2, 17, 106, 200])

In [5]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [6]:
type(array_1d)

numpy.ndarray

In [7]:
array_1d[0]

np.int64(-10)

In [8]:
array_1d[4]

np.int64(17)

In [9]:
array_1d[6]

np.int64(200)

In [10]:
array_1d[-1]

np.int64(200)

In [11]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [12]:
array_1d[0:3]

array([-10,  -2,   0])

In [13]:
array_1d[-1:-3]

array([], dtype=int64)

In [14]:
array_1d[-3:-1]

array([ 17, 106])

In [15]:
array_1d[:]

array([-10,  -2,   0,   2,  17, 106, 200])

In [16]:
array_1d[:3]

array([-10,  -2,   0])

In [17]:
array_1d[3:]

array([  2,  17, 106, 200])

In [18]:
array_1d[::]

array([-10,  -2,   0,   2,  17, 106, 200])

In [19]:
array_1d[::2]

array([-10,   0,  17, 200])

In [20]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [21]:
array_1d[::4]

array([-10,  17])

In [22]:
array_1d[0:3]

array([-10,  -2,   0])

In [23]:
array_1d[0:3:2]

array([-10,   0])

In [24]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [25]:
array_1d[-1]

np.int64(200)

In [26]:
array_1d[-2]

np.int64(106)

In [27]:
array_1d[-4]

np.int64(2)

In [28]:
array_1d[-5]

np.int64(0)

In [29]:
array_1d[-6]

np.int64(-2)

In [30]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [31]:
array_1d[1:-2]

array([-2,  0,  2, 17])

In [32]:
array_1d[:2]

array([-10,  -2])

In [33]:
array_1d[2:]

array([  0,   2,  17, 106, 200])

In [34]:
array_1d[:2], array_1d[2:]

(array([-10,  -2]), array([  0,   2,  17, 106, 200]))

In [35]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [36]:
array_1d[0]

np.int64(-10)

In [37]:
array_1d[0] = 100

In [38]:
array_1d

array([100,  -2,   0,   2,  17, 106, 200])