In [13]:
# at first, we need to install matplotlib using cmd/terminal
# pip install matplotlib

In [14]:
import matplotlib
print(matplotlib.__version__)


3.9.2


In [15]:
import matplotlib.pyplot as plt
import numpy as np 

In [16]:
x = np.arange(11)
y = x ** 2
print(x, y)

[ 0  1  2  3  4  5  6  7  8  9 10] [  0   1   4   9  16  25  36  49  64  81 100]


In [17]:
x, y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100]))

Basic Plotting

plt.scatter(x, y)